// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models
{
    public partial class Anh
    {
        public int Id { get; set; }
        public string Link { get; set; }
        public int MaSp { get; set; }

        public virtual SanPham MaSpNavigation { get; set; }
    }
}