// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models
{
    public partial class ChiTietHoaDon
    {
        public decimal SoLuong { get; set; }
        public int MaSp { get; set; }
        public int MaHd { get; set; }

        public virtual HoaDon MaHdNavigation { get; set; }
        public virtual SanPham MaSpNavigation { get; set; }
    }
}