// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models
{
    public partial class LoaiSanPham
    {
        public LoaiSanPham()
        {
            SanPham = new HashSet<SanPham>();
        }

        public int MaLsp { get; set; }
        public string TenSp { get; set; }

        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}