// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models
{
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            PhieuNhapKho = new HashSet<PhieuNhapKho>();
            TaiKhoan = new HashSet<TaiKhoan>();
            MaHd = new HashSet<HoaDon>();
        }

        public int IdnguoiDung { get; set; }
        public string TenNv { get; set; }
        public string TrangThai { get; set; }
        public string Loai { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }

        public virtual ICollection<PhieuNhapKho> PhieuNhapKho { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoan { get; set; }

        public virtual ICollection<HoaDon> MaHd { get; set; }
    }
}