// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models
{
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            MaPnk = new HashSet<PhieuNhapKho>();
        }

        public int MaNcc { get; set; }
        public string TenNcc { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string Sđt { get; set; }

        public virtual ICollection<PhieuNhapKho> MaPnk { get; set; }
    }
}