// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Models
{
    public partial class SanPham
    {
        public SanPham()
        {
            ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
            ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
        }

        public int MaSp { get; set; }
        public string TenSp { get; set; }
        public decimal GiaBan { get; set; }
        public string MoTa { get; set; }
        public decimal SltonHienTai { get; set; }
        public decimal SltonToiThieu { get; set; }
        public decimal GiaNhap { get; set; }
        public decimal? KhuyenMai { get; set; }
        public int MaLsp { get; set; }

        public virtual LoaiSanPham MaLspNavigation { get; set; }
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }
    }
}